import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

// Music terminology dictionary RU -> EN (expanded)
const musicDict: Record<string, string> = {
  // Moods & Emotions
  "душевно": "soulful",
  "душевный": "soulful",
  "грустно": "sad",
  "грустный": "melancholic",
  "весело": "upbeat",
  "веселый": "cheerful",
  "романтично": "romantic",
  "романтический": "romantic",
  "агрессивно": "aggressive",
  "агрессивный": "aggressive",
  "спокойно": "calm",
  "спокойный": "calm",
  "энергично": "energetic",
  "энергичный": "energetic",
  "меланхолично": "melancholic",
  "меланхоличный": "melancholic",
  "мрачно": "dark",
  "мрачный": "dark",
  "светло": "bright",
  "светлый": "bright",
  "мощно": "powerful",
  "мощный": "powerful",
  "нежно": "gentle",
  "нежный": "gentle",
  "драматично": "dramatic",
  "драматичный": "dramatic",
  "эпично": "epic",
  "эпичный": "epic",
  "таинственно": "mysterious",
  "таинственный": "mysterious",
  "громко": "loud",
  "громкий": "loud",
  "тихо": "soft",
  "тихий": "soft",
  "радостно": "joyful",
  "радостный": "joyful",
  "печально": "sorrowful",
  "печальный": "sorrowful",
  "тревожно": "anxious",
  "тревожный": "anxious",
  "воодушевляюще": "uplifting",
  "воодушевляющий": "uplifting",
  "вдохновляюще": "inspiring",
  "вдохновляющий": "inspiring",
  "торжественно": "triumphant",
  "торжественный": "triumphant",
  "возвышенно": "sublime",
  "возвышенный": "sublime",
  "интимно": "intimate",
  "интимный": "intimate",
  "страстно": "passionate",
  "страстный": "passionate",
  "задумчиво": "contemplative",
  "задумчивый": "contemplative",
  "мечтательно": "dreamy",
  "мечтательный": "dreamy",
  "игриво": "playful",
  "игривый": "playful",
  "дерзко": "edgy",
  "дерзкий": "edgy",
  "сексуально": "sensual",
  "сексуальный": "sensual",
  "бодро": "lively",
  "бодрый": "lively",
  "расслабленно": "relaxed",
  "расслабленный": "relaxed",
  "напряженно": "tense",
  "напряженный": "tense",
  "зловеще": "ominous",
  "зловещий": "ominous",
  "величественно": "majestic",
  "величественный": "majestic",
  "нервно": "nervous",
  "нервный": "nervous",
  "беззаботно": "carefree",
  "беззаботный": "carefree",
  "уверенно": "confident",
  "уверенный": "confident",
  "дикий": "wild",
  "дико": "wild",
  "безумно": "crazy",
  "безумный": "crazy",
  "сумасшедший": "insane",
  
  // Genres & Subgenres
  "поп": "pop",
  "поп-музыка": "pop music",
  "рок": "rock",
  "хард-рок": "hard rock",
  "софт-рок": "soft rock",
  "прогрессив-рок": "progressive rock",
  "прог-рок": "prog rock",
  "арт-рок": "art rock",
  "психоделик-рок": "psychedelic rock",
  "джаз": "jazz",
  "смуз-джаз": "smooth jazz",
  "фри-джаз": "free jazz",
  "бибоп": "bebop",
  "кул-джаз": "cool jazz",
  "эйсид-джаз": "acid jazz",
  "джаз-фанк": "jazz-funk",
  "блюз": "blues",
  "электрик-блюз": "electric blues",
  "чикаго-блюз": "Chicago blues",
  "дельта-блюз": "delta blues",
  "хип-хоп": "hip-hop",
  "хипхоп": "hip-hop",
  "олд-скул": "old school",
  "нью-скул": "new school",
  "бум-бэп": "boom bap",
  "рэп": "rap",
  "ганста-рэп": "gangsta rap",
  "сознательный рэп": "conscious rap",
  "электро": "electronic",
  "электронная": "electronic",
  "электронный": "electronic",
  "электроника": "electronica",
  "техно": "techno",
  "минимал-техно": "minimal techno",
  "детройт-техно": "Detroit techno",
  "хаус": "house",
  "дипхаус": "deep house",
  "дип-хаус": "deep house",
  "прогрессив-хаус": "progressive house",
  "тек-хаус": "tech house",
  "тропикал-хаус": "tropical house",
  "фанки-хаус": "funky house",
  "афро-хаус": "Afro house",
  "транс": "trance",
  "вокал-транс": "vocal trance",
  "прогрессив-транс": "progressive trance",
  "псай-транс": "psytrance",
  "гоа-транс": "Goa trance",
  "драм-н-бейс": "drum and bass",
  "драмнбейс": "drum and bass",
  "джангл": "jungle",
  "ликвид": "liquid drum and bass",
  "нейрофанк": "neurofunk",
  "дабстеп": "dubstep",
  "бростеп": "brostep",
  "регги": "reggae",
  "даб": "dub",
  "дансхолл": "dancehall",
  "ска-панк": "ska punk",
  "фанк": "funk",
  "пи-фанк": "P-funk",
  "соул": "soul",
  "нео-соул": "neo-soul",
  "r&b": "R&B",
  "рнб": "R&B",
  "ритм-энд-блюз": "rhythm and blues",
  "кантри": "country",
  "кантри-рок": "country rock",
  "блюграсс": "bluegrass",
  "американа": "Americana",
  "фолк": "folk",
  "инди-фолк": "indie folk",
  "народная": "folk",
  "этно": "ethnic",
  "этническая": "world music",
  "ворлд": "world",
  "классика": "classical",
  "классическая": "classical",
  "классический": "classical",
  "неоклассика": "neoclassical",
  "барокко": "baroque",
  "ренессанс": "renaissance",
  "симфоническая": "symphonic",
  "симфонический": "symphonic",
  "камерная": "chamber",
  "опера": "opera",
  "оперетта": "operetta",
  "метал": "metal",
  "металл": "metal",
  "хеви-метал": "heavy metal",
  "трэш-метал": "thrash metal",
  "дэт-метал": "death metal",
  "блэк-метал": "black metal",
  "пауэр-метал": "power metal",
  "симфо-метал": "symphonic metal",
  "ню-метал": "nu metal",
  "металкор": "metalcore",
  "дэткор": "deathcore",
  "панк": "punk",
  "хардкор-панк": "hardcore punk",
  "поп-панк": "pop punk",
  "пост-хардкор": "post-hardcore",
  "эмо": "emo",
  "эмокор": "emocore",
  "скримо": "screamo",
  "инди": "indie",
  "инди-рок": "indie rock",
  "инди-поп": "indie pop",
  "альтернатива": "alternative",
  "альтернативный": "alternative",
  "альт-рок": "alt-rock",
  "латино": "Latin",
  "латинский": "Latin",
  "сальса": "salsa",
  "бачата": "bachata",
  "реггетон": "reggaeton",
  "кумбия": "cumbia",
  "танго": "tango",
  "босса-нова": "bossa nova",
  "самба": "samba",
  "диско": "disco",
  "ню-диско": "nu-disco",
  "итало-диско": "Italo disco",
  "синтипоп": "synthpop",
  "синти-поп": "synthpop",
  "электропоп": "electropop",
  "дарквейв": "darkwave",
  "колдвейв": "coldwave",
  "ретро": "retro",
  "80-е": "80s",
  "восьмидесятые": "80s",
  "90-е": "90s",
  "девяностые": "90s",
  "2000-е": "2000s",
  "нулевые": "2000s",
  "лоу-фай": "lo-fi",
  "лофай": "lo-fi",
  "чилл": "chill",
  "чиллаут": "chillout",
  "чилл-хоп": "chillhop",
  "амбиент": "ambient",
  "эмбиент": "ambient",
  "дарк-амбиент": "dark ambient",
  "дроун": "drone",
  "госпел": "gospel",
  "спиричуэлс": "spirituals",
  "свинг-жанр": "swing",
  "биг-бенд": "big band",
  "ска": "ska",
  "гранж": "grunge",
  "шугейз": "shoegaze",
  "дрим-поп": "dream pop",
  "постпанк": "post-punk",
  "пост-панк": "post-punk",
  "пост-рок": "post-rock",
  "пост-метал": "post-metal",
  "синтвейв": "synthwave",
  "ретровейв": "retrowave",
  "аутран": "outrun",
  "вейпорвейв": "vaporwave",
  "фьючер-бейс": "future bass",
  "фьючер-гараж": "future garage",
  "трэп": "trap",
  "трэп-музыка": "trap music",
  "футворк": "footwork",
  "джук": "juke",
  "гэридж": "UK garage",
  "грайм": "grime",
  "бейсмент": "UK bass",
  "IDM": "IDM",
  "глитч": "glitch",
  "нойз": "noise",
  "экспериментал": "experimental",
  "авангард": "avant-garde",
  "мат-рок": "math rock",
  "пост-бит": "post-beat",
  "брейкбит": "breakbeat",
  "биг-бит": "big beat",
  "брейкс": "breaks",
  "гоа": "Goa",
  "хардстайл": "hardstyle",
  "хард-дэнс": "hard dance",
  "хэппи-хардкор": "happy hardcore",
  "габбер": "gabber",
  "спидкор": "speedcore",
  "индастриал": "industrial",
  "EBM": "EBM",
  "эгбит": "aggrotech",
  "кибер-панк": "cyberpunk",
  "ки-поп": "K-pop",
  "джей-поп": "J-pop",
  "аниме": "anime",
  "игровая": "video game music",
  "саундтрек": "soundtrack",
  "кинематографический": "cinematic",
  "эпик": "epic orchestral",
  "трейлер-музыка": "trailer music",
  
  // Vocals & Singing Styles
  "мужской": "male",
  "мужчина": "male",
  "женский": "female",
  "женщина": "female",
  "голос": "vocals",
  "вокал": "vocals",
  "вокальный": "vocal",
  "поет": "singing",
  "пою": "singing",
  "спеть": "sing",
  "петь": "singing",
  "унисон": "unison harmony",
  "в унисон": "in unison",
  "хор": "choir",
  "хоровой": "choral",
  "хоровое": "choral",
  "рэпует": "rapping",
  "читает рэп": "rapping",
  "речитатив": "spoken word",
  "разговорный": "spoken",
  "шепот": "whisper",
  "шепотом": "whispered",
  "крик": "screaming",
  "кричит": "screaming",
  "орет": "shouting",
  "гроулинг": "growling",
  "гроул": "growl",
  "скрим": "scream",
  "скриминг": "screaming vocals",
  "фальцет": "falsetto",
  "бэк-вокал": "backing vocals",
  "бэк": "backing",
  "подпевка": "backing vocals",
  "дуэт": "duet",
  "трио": "trio",
  "квартет": "quartet",
  "соло-вокал": "solo vocals",
  "сопрано": "soprano",
  "альт": "alto",
  "тенор": "tenor",
  "баритон": "baritone",
  "бас-голос": "bass voice",
  "вибрато": "vibrato",
  "мелизмы": "melisma",
  "йодль": "yodeling",
  "автотюн": "auto-tune",
  "вокодер": "vocoder",
  "битбокс": "beatbox",
  "скат": "scat singing",
  "речь": "speech",
  "нарратив": "narrative",
  "рассказ": "storytelling",
  
  // Instruments (expanded)
  "гитара": "guitar",
  "электрогитара": "electric guitar",
  "электро-гитара": "electric guitar",
  "акустическая": "acoustic",
  "акустическая гитара": "acoustic guitar",
  "классическая гитара": "classical guitar",
  "нейлоновая гитара": "nylon string guitar",
  "12-струнная гитара": "12-string guitar",
  "слайд-гитара": "slide guitar",
  "педал-стил": "pedal steel",
  "бас": "bass",
  "бас-гитара": "bass guitar",
  "электробас": "electric bass",
  "безладовый бас": "fretless bass",
  "слэп-бас": "slap bass",
  "синт-бас": "synth bass",
  "808": "808 bass",
  "саб-бас": "sub bass",
  "барабаны": "drums",
  "ударные": "drums",
  "живые барабаны": "live drums",
  "электронные барабаны": "electronic drums",
  "драм-машина": "drum machine",
  "семплированные барабаны": "sampled drums",
  "перкуссия": "percussion",
  "хай-хэт": "hi-hat",
  "бочка": "kick drum",
  "малый барабан": "snare drum",
  "том": "tom",
  "райд": "ride cymbal",
  "крэш": "crash cymbal",
  "тарелки": "cymbals",
  "пианино": "piano",
  "фортепиано": "piano",
  "электропиано": "electric piano",
  "родес": "Rhodes",
  "вурлитцер": "Wurlitzer",
  "рояль": "grand piano",
  "концертный рояль": "concert grand piano",
  "пиано": "piano",
  "клавишные": "keyboards",
  "клавиши": "keys",
  "синтезатор": "synthesizer",
  "синт": "synth",
  "моог": "Moog",
  "аналоговый синтезатор": "analog synth",
  "цифровой синтезатор": "digital synth",
  "модульный синтезатор": "modular synth",
  "пэды": "synth pads",
  "лиды": "synth leads",
  "арпеджиатор": "arpeggiator",
  "арпеджио": "arpeggio",
  "секвенсор": "sequencer",
  "скрипка": "violin",
  "скрипки": "violins",
  "альт-скрипка": "viola",
  "виола": "viola",
  "виолончель": "cello",
  "виолончели": "cellos",
  "контрабас": "double bass",
  "струнный квартет": "string quartet",
  "струнный оркестр": "string orchestra",
  "струнные": "strings",
  "пиццикато": "pizzicato",
  "тремоло": "tremolo",
  "легато": "legato",
  "стаккато": "staccato",
  "саксофон": "saxophone",
  "сакс": "sax",
  "альт-саксофон": "alto saxophone",
  "тенор-саксофон": "tenor saxophone",
  "сопрано-саксофон": "soprano saxophone",
  "баритон-саксофон": "baritone saxophone",
  "труба": "trumpet",
  "флюгельгорн": "flugelhorn",
  "тромбон": "trombone",
  "валторна": "French horn",
  "туба": "tuba",
  "духовая секция": "brass section",
  "биг-бенд-брасс": "big band brass",
  "флейта": "flute",
  "пикколо": "piccolo",
  "кларнет": "clarinet",
  "гобой": "oboe",
  "фагот": "bassoon",
  "арфа": "harp",
  "орган": "organ",
  "церковный орган": "church organ",
  "хаммонд-орган": "Hammond organ",
  "укулеле": "ukulele",
  "банджо": "banjo",
  "мандолина": "mandolin",
  "ситар": "sitar",
  "кото": "koto",
  "эрху": "erhu",
  "балалайка": "balalaika",
  "домра": "domra",
  "баян": "bayan",
  "аккордеон": "accordion",
  "губная гармошка": "harmonica",
  "гармоника": "harmonica",
  "маракасы": "maracas",
  "бонго": "bongos",
  "конга": "congas",
  "джембе": "djembe",
  "кахон": "cajon",
  "тамбурин": "tambourine",
  "бубен": "tambourine",
  "треугольник": "triangle",
  "кастаньеты": "castanets",
  "ковбелл": "cowbell",
  "шейкер": "shaker",
  "клавес": "claves",
  "ксилофон": "xylophone",
  "маримба": "marimba",
  "вибрафон": "vibraphone",
  "глокеншпиль": "glockenspiel",
  "колокола": "bells",
  "колокольчики": "chimes",
  "тубулярные колокола": "tubular bells",
  "литавры": "timpani",
  "тимпаны": "timpani",
  "большой барабан": "bass drum",
  "гонг": "gong",
  "тамтам": "tam-tam",
  "деревянные духовые": "woodwinds",
  "духовые": "brass",
  "медные духовые": "brass instruments",
  "оркестр": "orchestra",
  "оркестровый": "orchestral",
  "симфонический оркестр": "symphony orchestra",
  "камерный оркестр": "chamber orchestra",
  "ансамбль": "ensemble",
  "бэнд": "band",
  "группа": "band",
  "живой бэнд": "live band",
  "терменвокс": "theremin",
  "варган": "jaw harp",
  "калимба": "kalimba",
  "стилпан": "steel pan",
  "стил-драм": "steel drum",
  "диджериду": "didgeridoo",
  "волынка": "bagpipes",
  "окарина": "ocarina",
  "панфлейта": "pan flute",
  "блок-флейта": "recorder",
  
  // Tempo, Rhythm & BPM
  "быстро": "fast tempo",
  "быстрый": "fast",
  "очень быстро": "very fast",
  "молниеносно": "lightning fast",
  "медленно": "slow tempo",
  "медленный": "slow",
  "очень медленно": "very slow",
  "средний темп": "mid-tempo",
  "среднетемповый": "mid-tempo",
  "умеренно": "moderate tempo",
  "умеренный": "moderate",
  "ритм": "rhythm",
  "ритме": "rhythm",
  "в ритме": "with the rhythm of",
  "ритмичный": "rhythmic",
  "ритмичная": "rhythmic",
  "скорость": "BPM",
  "темп": "tempo",
  "бит": "beat",
  "биты": "beats",
  "четкий бит": "punchy beat",
  "тяжелый бит": "heavy beat",
  "грув": "groove",
  "грувовый": "groovy",
  "фанковый грув": "funky groove",
  "свинг": "swing feel",
  "свингующий": "swinging",
  "шаффл": "shuffle",
  "синкопа": "syncopation",
  "синкопированный": "syncopated",
  "полиритм": "polyrhythm",
  "полиритмия": "polyrhythmic",
  "кросс-ритм": "cross-rhythm",
  "офф-бит": "off-beat",
  "даунбит": "downbeat",
  "апбит": "upbeat",
  "триоль": "triplet",
  "триольный": "triplet feel",
  "четвертные ноты": "quarter notes",
  "восьмые ноты": "eighth notes",
  "шестнадцатые": "sixteenth notes",
  "пунктирный ритм": "dotted rhythm",
  "двойной бас": "double bass drum",
  "бласт-бит": "blast beat",
  "брейкбитовый": "breakbeat",
  "четырехчетвертной": "four on the floor",
  "4/4": "4/4 time",
  "3/4": "3/4 time waltz",
  "6/8": "6/8 time",
  "нечетный размер": "odd time signature",
  "5/4": "5/4 time",
  "7/8": "7/8 time",
  
  // Song Structure
  "куплет": "verse",
  "куплеты": "verses",
  "припев": "chorus",
  "припевы": "choruses",
  "бридж": "bridge",
  "пре-припев": "pre-chorus",
  "пост-припев": "post-chorus",
  "вступление": "intro",
  "интро": "intro",
  "аутро": "outro",
  "концовка": "ending",
  "финал": "finale",
  "соло": "solo",
  "гитарное соло": "guitar solo",
  "инструментальная часть": "instrumental section",
  "брейк": "break",
  "брейкдаун": "breakdown",
  "дроп": "drop",
  "билдап": "buildup",
  "кульминация": "climax",
  "развязка": "resolution",
  "переход": "transition",
  "модуляция": "modulation",
  "ключевая смена": "key change",
  "кода": "coda",
  "рифф": "riff",
  "гитарный рифф": "guitar riff",
  "басовый рифф": "bass riff",
  "хук": "hook",
  "мотив": "motif",
  "тема": "theme",
  "вариация": "variation",
  "повтор": "repetition",
  "зацикленный": "looped",
  "лупинг": "looping",
  "секция": "section",
  
  // Sound & Production
  "дополняя": "complementing",
  "гармония": "harmony",
  "гармоничный": "harmonious",
  "гармонии": "harmonies",
  "мелодия": "melody",
  "мелодичный": "melodic",
  "мелодии": "melodies",
  "контрмелодия": "counter-melody",
  "басовый": "bassy",
  "низкий": "low",
  "низкие частоты": "low frequencies",
  "сабы": "sub frequencies",
  "высокий": "high",
  "высокие частоты": "high frequencies",
  "средние частоты": "mid frequencies",
  "глубокий": "deep",
  "глубина": "depth",
  "легкий": "light",
  "тяжелый": "heavy",
  "плавный": "smooth",
  "плавность": "smoothness",
  "резкий": "sharp",
  "резкость": "sharpness",
  "теплый": "warm",
  "теплота": "warmth",
  "холодный": "cold",
  "ледяной": "icy",
  "чистый": "clean",
  "чистота": "clarity",
  "грязный": "dirty",
  "грязь": "grit",
  "искаженный": "distorted",
  "дисторшн": "distortion",
  "овердрайв": "overdrive",
  "фуз": "fuzz",
  "кранч": "crunch",
  "хайгейн": "high gain",
  "реверб": "reverb",
  "ревер": "reverb",
  "холл-реверб": "hall reverb",
  "плейт-реверб": "plate reverb",
  "рум-реверб": "room reverb",
  "эхо": "echo",
  "дилей": "delay",
  "задержка": "delay",
  "пинг-понг дилей": "ping-pong delay",
  "хорус": "chorus effect",
  "фленжер": "flanger",
  "фейзер": "phaser",
  "вибрато-эффект": "vibrato effect",
  "тремоло-эффект": "tremolo effect",
  "вау-вау": "wah-wah",
  "токбокс": "talkbox",
  "компрессия": "compression",
  "компрессор": "compressor",
  "сайдчейн": "sidechain",
  "дакинг": "ducking",
  "лимитер": "limiter",
  "сатурация": "saturation",
  "гармоники": "harmonics",
  "обертоны": "overtones",
  "атмосферный": "atmospheric",
  "атмосфера": "atmosphere",
  "космический": "cosmic",
  "космос": "space",
  "пространственный": "spacious",
  "широкий": "wide",
  "узкий": "narrow",
  "панорама": "stereo pan",
  "моно": "mono",
  "стерео": "stereo",
  "объемный": "surround",
  "3D-звук": "3D audio",
  "футуристический": "futuristic",
  "ностальгический": "nostalgic",
  "ностальгия": "nostalgia",
  "винтажный": "vintage",
  "ретро-звук": "retro sound",
  "современный": "modern",
  "свежий": "fresh",
  "полированный": "polished",
  "сырой": "raw",
  "необработанный": "unpolished",
  "минималистичный": "minimalist",
  "минимализм": "minimalism",
  "максималистичный": "maximalist",
  "насыщенный": "rich",
  "плотный": "dense",
  "разреженный": "sparse",
  "экспериментальный": "experimental",
  "психоделический": "psychedelic",
  "гипнотический": "hypnotic",
  "транс-музыка": "trance-inducing",
  "медитативный": "meditative",
  "зен": "zen",
  "танцевальный": "danceable",
  "клубный": "club",
  "клуб": "club music",
  "рейв": "rave",
  "фестивальный": "festival",
  "радио": "radio-friendly",
  "радиоформат": "radio format",
  "хитовый": "hit potential",
  "коммерческий": "commercial",
  "попсовый": "poppy",
  "андеграунд": "underground",
  "андеграундный": "underground",
  "инструментальный": "instrumental",
  "инструментал": "instrumental track",
  "без вокала": "no vocals",
  "а капелла": "a cappella",
  "акапелла": "a cappella",
  "только голос": "vocals only",
  "живой": "live",
  "живое звучание": "live sound",
  "студийный": "studio",
  "студийное качество": "studio quality",
  "хай-фай": "hi-fi",
  "lo-fi стиль": "lo-fi style",
  "аналоговый": "analog",
  "аналоговое звучание": "analog sound",
  "цифровой": "digital",
  "сэмплированный": "sampled",
  "сэмплы": "samples",
  "сэмплирование": "sampling",
  "чоп": "chop",
  "чопнутый": "chopped",
  "импровизация": "improvisation",
  "импровизированный": "improvised",
  "джем": "jam",
  "джем-сессия": "jam session",
  
  // Dynamics
  "тихий-громкий": "quiet to loud",
  "крещендо": "crescendo",
  "нарастание": "building",
  "нарастающий": "building up",
  "диминуэндо": "diminuendo",
  "затухание": "fading",
  "затухающий": "fading out",
  "динамика-пиано": "piano (soft)",
  "меццо-пиано": "mezzo-piano",
  "меццо-форте": "mezzo-forte",
  "форте": "forte (loud)",
  "фортиссимо": "fortissimo",
  "пианиссимо": "pianissimo",
  "акцент": "accent",
  "акцентированный": "accented",
  "взрывной": "explosive",
  "взрыв": "explosion",
  
  // Russian-specific connectors and phrases
  "и": "and",
  "в": "with",
  "с": "with",
  "на": "on",
  "для": "for",
  "как": "like",
  "или": "or",
  "иногда": "sometimes",
  "друг друга": "each other",
  "вместе": "together",
  "попеременно": "alternating",
  "чередуя": "alternating",
  "переходя": "transitioning",
  "постепенно": "gradually",
  "внезапно": "suddenly",
  "плавно переходя": "smoothly transitioning",
  "в стиле": "in the style of",
  "под влиянием": "influenced by",
  "напоминает": "reminiscent of",
  "похоже на": "similar to",
  "смесь": "blend of",
  "микс": "mix of",
  "сочетание": "combination of",
  "слияние": "fusion of",
  "элементы": "elements of",
  "оттенки": "hints of",
  "нотки": "touches of",
};

// Translate Russian music description to English
function translateMusicPrompt(text: string): string {
  let result = text.toLowerCase();
  
  // Extract and preserve numbers (BPM, etc.)
  const numbers = result.match(/\d+/g) || [];
  
  // Sort dictionary by key length (longest first) to avoid partial replacements
  const sortedEntries = Object.entries(musicDict).sort((a, b) => b[0].length - a[0].length);
  
  for (const [ru, en] of sortedEntries) {
    const regex = new RegExp(ru, 'gi');
    result = result.replace(regex, en);
  }
  
  // Handle BPM pattern (e.g., "144 скорость" -> "144 BPM")
  result = result.replace(/(\d+)\s*BPM/gi, '$1 BPM');
  
  // Clean up extra spaces
  result = result.replace(/\s+/g, ' ').trim();
  
  // Capitalize first letter
  result = result.charAt(0).toUpperCase() + result.slice(1);
  
  return result;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { content } = await req.json();
    
    console.log("Boost style request:", { content });

    // Translate Russian to English music prompt
    const translatedContent = translateMusicPrompt(content);
    console.log("Translated content:", translatedContent);

    const SUNO_API_KEY = Deno.env.get("SUNO_API_KEY");
    if (!SUNO_API_KEY) {
      throw new Error("SUNO_API_KEY not configured");
    }

    // Call Suno API to boost style
    const response = await fetch("https://api.sunoapi.org/api/v1/style/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${SUNO_API_KEY}`,
      },
      body: JSON.stringify({ 
        content: translatedContent,
      }),
    });

    const result = await response.json();
    console.log("Suno Style Boost API response:", result);

    if (result.code !== 200) {
      // If Suno API fails, return the translated content as boosted style
      console.log("Suno API failed, returning translated content");
      return new Response(
        JSON.stringify({ 
          success: true, 
          boostedStyle: translatedContent,
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Check if we got the result directly in the response
    const boostedStyle = result.data?.result || result.data?.style || result.data?.content;
    
    if (boostedStyle) {
      return new Response(
        JSON.stringify({ 
          success: true, 
          boostedStyle,
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Fallback: return translated content
    return new Response(
      JSON.stringify({ 
        success: true, 
        boostedStyle: translatedContent,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: unknown) {
    console.error("Error in boost-style:", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
