export const musicDictPart3: Record<string, string> = {
  "куплет": "verse",
  "куплеты": "verses",
  "припев": "chorus",
  "припевы": "choruses",
  "бридж": "bridge",
  "пре-припев": "pre-chorus",
  "пост-припев": "post-chorus",
  "вступление": "intro",
  "интро": "intro",
  "аутро": "outro",
  "концовка": "ending",
  "финал": "finale",
  "соло": "solo",
  "гитарное соло": "guitar solo",
  "инструментальная часть": "instrumental section",
  "брейк": "break",
  "брейкдаун": "breakdown",
  "дроп": "drop",
  "билдап": "buildup",
  "кульминация": "climax",
  "развязка": "resolution",
  "переход": "transition",
  "модуляция": "modulation",
  "ключевая смена": "key change",
  "кода": "coda",
  "рифф": "riff",
  "гитарный рифф": "guitar riff",
  "басовый рифф": "bass riff",
  "хук": "hook",
  "мотив": "motif",
  "тема": "theme",
  "вариация": "variation",
  "повтор": "repetition",
  "зацикленный": "looped",
  "лупинг": "looping",
  "секция": "section",
  "дополняя": "complementing",
  "гармония": "harmony",
  "гармоничный": "harmonious",
  "гармонии": "harmonies",
  "мелодия": "melody",
  "мелодичный": "melodic",
  "мелодии": "melodies",
  "контрмелодия": "counter-melody",
  "басовый": "bassy",
  "низкий": "low",
  "низкие частоты": "low frequencies",
  "сабы": "sub frequencies",
  "высокий": "high",
  "высокие частоты": "high frequencies",
  "средние частоты": "mid frequencies",
  "глубокий": "deep",
  "глубина": "depth",
  "легкий": "light",
  "тяжелый": "heavy",
  "плавный": "smooth",
  "плавность": "smoothness",
  "резкий": "sharp",
  "резкость": "sharpness",
  "теплый": "warm",
  "теплота": "warmth",
  "холодный": "cold",
  "ледяной": "icy",
  "чистый": "clean",
  "чистота": "clarity",
  "грязный": "dirty",
  "грязь": "grit",
  "искаженный": "distorted",
  "дисторшн": "distortion",
  "овердрайв": "overdrive",
  "фуз": "fuzz",
  "кранч": "crunch",
  "хайгейн": "high gain",
  "реверб": "reverb",
  "ревер": "reverb",
  "холл-реверб": "hall reverb",
  "плейт-реверб": "plate reverb",
  "рум-реверб": "room reverb",
  "эхо": "echo",
  "дилей": "delay",
  "задержка": "delay",
  "пинг-понг дилей": "ping-pong delay",
  "хорус": "chorus effect",
  "фленжер": "flanger",
  "фейзер": "phaser",
  "вибрато-эффект": "vibrato effect",
  "тремоло-эффект": "tremolo effect",
  "вау-вау": "wah-wah",
  "токбокс": "talkbox",
  "компрессия": "compression",
  "компрессор": "compressor",
  "сайдчейн": "sidechain",
  "дакинг": "ducking",
  "лимитер": "limiter",
  "сатурация": "saturation",
  "гармоники": "harmonics",
  "обертоны": "overtones",
  "атмосферный": "atmospheric",
  "атмосфера": "atmosphere",
  "космический": "cosmic",
  "космос": "space",
  "пространственный": "spacious",
  "широкий": "wide",
  "узкий": "narrow",
  "панорама": "stereo pan",
  "моно": "mono",
  "стерео": "stereo",
  "объемный": "surround",
  "3D-звук": "3D audio",
  "футуристический": "futuristic",
  "ностальгический": "nostalgic",
  "ностальгия": "nostalgia",
  "винтажный": "vintage",
  "ретро-звук": "retro sound",
  "современный": "modern",
  "свежий": "fresh",
  "полированный": "polished",
  "сырой": "raw",
  "необработанный": "unpolished",
  "минималистичный": "minimalist",
  "минимализм": "minimalism",
  "максималистичный": "maximalist",
  "насыщенный": "rich",
  "плотный": "dense",
  "разреженный": "sparse",
  "экспериментальный": "experimental",
  "психоделический": "psychedelic",
  "гипнотический": "hypnotic",
  "транс-музыка": "trance-inducing",
  "медитативный": "meditative",
  "зен": "zen",
  "танцевальный": "danceable",
  "клубный": "club",
  "клуб": "club music",
  "рейв": "rave",
  "фестивальный": "festival",
  "радио": "radio-friendly",
  "радиоформат": "radio format",
  "хитовый": "hit potential",
  "коммерческий": "commercial",
  "попсовый": "poppy",
  "андеграунд": "underground",
  "андеграундный": "underground",
  "инструментальный": "instrumental",
  "инструментал": "instrumental track",
  "без вокала": "no vocals",
  "а капелла": "a cappella",
  "акапелла": "a cappella",
  "только голос": "vocals only",
  "живой": "live",
  "живое звучание": "live sound",
  "студийный": "studio",
  "студийное качество": "studio quality",
  "хай-фай": "hi-fi",
  "lo-fi стиль": "lo-fi style",
  "аналоговый": "analog",
  "аналоговое звучание": "analog sound",
  "цифровой": "digital",
  "сэмплированный": "sampled",
  "сэмплы": "samples",
  "сэмплирование": "sampling",
  "чоп": "chop",
  "чопнутый": "chopped",
  "импровизация": "improvisation",
  "импровизированный": "improvised",
  "джем": "jam",
  "джем-сессия": "jam session",
  "тихий-громкий": "quiet to loud",
  "крещендо": "crescendo",
  "нарастание": "building",
  "нарастающий": "building up",
  "диминуэндо": "diminuendo",
  "затухание": "fading",
  "затухающий": "fading out",
  "динамика-пиано": "piano (soft)",
  "меццо-пиано": "mezzo-piano",
  "меццо-форте": "mezzo-forte",
  "форте": "forte (loud)",
  "фортиссимо": "fortissimo",
  "пианиссимо": "pianissimo",
  "акцент": "accent",
  "акцентированный": "accented",
  "взрывной": "explosive",
  "взрыв": "explosion",
  "и": "and",
  "в": "with",
  "с": "with",
  "на": "on",
  "для": "for",
  "как": "like",
  "или": "or",
  "иногда": "sometimes",
  "друг друга": "each other",
  "вместе": "together",
  "попеременно": "alternating",
  "чередуя": "alternating",
  "переходя": "transitioning",
  "постепенно": "gradually",
  "внезапно": "suddenly",
  "плавно переходя": "smoothly transitioning",
  "в стиле": "in the style of",
  "под влиянием": "influenced by",
  "напоминает": "reminiscent of",
  "похоже на": "similar to",
  "смесь": "blend of",
  "микс": "mix of",
  "сочетание": "combination of",
  "слияние": "fusion of",
  "элементы": "elements of",
  "оттенки": "hints of",
  "нотки": "touches of",
};
