export const musicDictPart2: Record<string, string> = {
  "гитара": "guitar",
  "электрогитара": "electric guitar",
  "электро-гитара": "electric guitar",
  "акустическая": "acoustic",
  "акустическая гитара": "acoustic guitar",
  "классическая гитара": "classical guitar",
  "нейлоновая гитара": "nylon string guitar",
  "12-струнная гитара": "12-string guitar",
  "слайд-гитара": "slide guitar",
  "педал-стил": "pedal steel",
  "бас": "bass",
  "бас-гитара": "bass guitar",
  "электробас": "electric bass",
  "безладовый бас": "fretless bass",
  "слэп-бас": "slap bass",
  "синт-бас": "synth bass",
  "808": "808 bass",
  "саб-бас": "sub bass",
  "барабаны": "drums",
  "ударные": "drums",
  "живые барабаны": "live drums",
  "электронные барабаны": "electronic drums",
  "драм-машина": "drum machine",
  "семплированные барабаны": "sampled drums",
  "перкуссия": "percussion",
  "хай-хэт": "hi-hat",
  "бочка": "kick drum",
  "малый барабан": "snare drum",
  "том": "tom",
  "райд": "ride cymbal",
  "крэш": "crash cymbal",
  "тарелки": "cymbals",
  "пианино": "piano",
  "фортепиано": "piano",
  "электропиано": "electric piano",
  "родес": "Rhodes",
  "вурлитцер": "Wurlitzer",
  "рояль": "grand piano",
  "концертный рояль": "concert grand piano",
  "пиано": "piano",
  "клавишные": "keyboards",
  "клавиши": "keys",
  "синтезатор": "synthesizer",
  "синт": "synth",
  "моог": "Moog",
  "аналоговый синтезатор": "analog synth",
  "цифровой синтезатор": "digital synth",
  "модульный синтезатор": "modular synth",
  "пэды": "synth pads",
  "лиды": "synth leads",
  "арпеджиатор": "arpeggiator",
  "арпеджио": "arpeggio",
  "секвенсор": "sequencer",
  "скрипка": "violin",
  "скрипки": "violins",
  "альт-скрипка": "viola",
  "виола": "viola",
  "виолончель": "cello",
  "виолончели": "cellos",
  "контрабас": "double bass",
  "струнный квартет": "string quartet",
  "струнный оркестр": "string orchestra",
  "струнные": "strings",
  "пиццикато": "pizzicato",
  "тремоло": "tremolo",
  "легато": "legato",
  "стаккато": "staccato",
  "саксофон": "saxophone",
  "сакс": "sax",
  "альт-саксофон": "alto saxophone",
  "тенор-саксофон": "tenor saxophone",
  "сопрано-саксофон": "soprano saxophone",
  "баритон-саксофон": "baritone saxophone",
  "труба": "trumpet",
  "флюгельгорн": "flugelhorn",
  "тромбон": "trombone",
  "валторна": "French horn",
  "туба": "tuba",
  "духовая секция": "brass section",
  "биг-бенд-брасс": "big band brass",
  "флейта": "flute",
  "пикколо": "piccolo",
  "кларнет": "clarinet",
  "гобой": "oboe",
  "фагот": "bassoon",
  "арфа": "harp",
  "орган": "organ",
  "церковный орган": "church organ",
  "хаммонд-орган": "Hammond organ",
  "укулеле": "ukulele",
  "банджо": "banjo",
  "мандолина": "mandolin",
  "ситар": "sitar",
  "кото": "koto",
  "эрху": "erhu",
  "балалайка": "balalaika",
  "домра": "domra",
  "баян": "bayan",
  "аккордеон": "accordion",
  "губная гармошка": "harmonica",
  "гармоника": "harmonica",
  "маракасы": "maracas",
  "бонго": "bongos",
  "конга": "congas",
  "джембе": "djembe",
  "кахон": "cajon",
  "тамбурин": "tambourine",
  "бубен": "tambourine",
  "треугольник": "triangle",
  "кастаньеты": "castanets",
  "ковбелл": "cowbell",
  "шейкер": "shaker",
  "клавес": "claves",
  "ксилофон": "xylophone",
  "маримба": "marimba",
  "вибрафон": "vibraphone",
  "глокеншпиль": "glockenspiel",
  "колокола": "bells",
  "колокольчики": "chimes",
  "тубулярные колокола": "tubular bells",
  "литавры": "timpani",
  "тимпаны": "timpani",
  "большой барабан": "bass drum",
  "гонг": "gong",
  "тамтам": "tam-tam",
  "деревянные духовые": "woodwinds",
  "духовые": "brass",
  "медные духовые": "brass instruments",
  "оркестр": "orchestra",
  "оркестровый": "orchestral",
  "симфонический оркестр": "symphony orchestra",
  "камерный оркестр": "chamber orchestra",
  "ансамбль": "ensemble",
  "бэнд": "band",
  "группа": "band",
  "живой бэнд": "live band",
  "терменвокс": "theremin",
  "варган": "jaw harp",
  "калимба": "kalimba",
  "стилпан": "steel pan",
  "стил-драм": "steel drum",
  "диджериду": "didgeridoo",
  "волынка": "bagpipes",
  "окарина": "ocarina",
  "панфлейта": "pan flute",
  "блок-флейта": "recorder",
  "быстро": "fast tempo",
  "быстрый": "fast",
  "очень быстро": "very fast",
  "молниеносно": "lightning fast",
  "медленно": "slow tempo",
  "медленный": "slow",
  "очень медленно": "very slow",
  "средний темп": "mid-tempo",
  "среднетемповый": "mid-tempo",
  "умеренно": "moderate tempo",
  "умеренный": "moderate",
  "ритм": "rhythm",
  "ритме": "rhythm",
  "в ритме": "with the rhythm of",
  "ритмичный": "rhythmic",
  "ритмичная": "rhythmic",
  "скорость": "BPM",
  "темп": "tempo",
  "бит": "beat",
  "биты": "beats",
  "четкий бит": "punchy beat",
  "тяжелый бит": "heavy beat",
  "грув": "groove",
  "грувовый": "groovy",
  "фанковый грув": "funky groove",
  "свинг": "swing feel",
  "свингующий": "swinging",
  "шаффл": "shuffle",
  "синкопа": "syncopation",
  "синкопированный": "syncopated",
  "полиритм": "polyrhythm",
  "полиритмия": "polyrhythmic",
  "кросс-ритм": "cross-rhythm",
  "офф-бит": "off-beat",
  "даунбит": "downbeat",
  "апбит": "upbeat",
  "триоль": "triplet",
  "триольный": "triplet feel",
  "четвертные ноты": "quarter notes",
  "восьмые ноты": "eighth notes",
  "шестнадцатые": "sixteenth notes",
  "пунктирный ритм": "dotted rhythm",
  "двойной бас": "double bass drum",
  "бласт-бит": "blast beat",
  "брейкбитовый": "breakbeat",
  "четырехчетвертной": "four on the floor",
  "4/4": "4/4 time",
  "3/4": "3/4 time waltz",
  "6/8": "6/8 time",
  "нечетный размер": "odd time signature",
  "5/4": "5/4 time",
  "7/8": "7/8 time",
};
