export const musicDictPart1: Record<string, string> = {
  "душевно": "soulful",
  "душевный": "soulful",
  "грустно": "sad",
  "грустный": "melancholic",
  "весело": "upbeat",
  "веселый": "cheerful",
  "романтично": "romantic",
  "романтический": "romantic",
  "агрессивно": "aggressive",
  "агрессивный": "aggressive",
  "спокойно": "calm",
  "спокойный": "calm",
  "энергично": "energetic",
  "энергичный": "energetic",
  "меланхолично": "melancholic",
  "меланхоличный": "melancholic",
  "мрачно": "dark",
  "мрачный": "dark",
  "светло": "bright",
  "светлый": "bright",
  "мощно": "powerful",
  "мощный": "powerful",
  "нежно": "gentle",
  "нежный": "gentle",
  "драматично": "dramatic",
  "драматичный": "dramatic",
  "эпично": "epic",
  "эпичный": "epic",
  "таинственно": "mysterious",
  "таинственный": "mysterious",
  "громко": "loud",
  "громкий": "loud",
  "тихо": "soft",
  "тихий": "soft",
  "радостно": "joyful",
  "радостный": "joyful",
  "печально": "sorrowful",
  "печальный": "sorrowful",
  "тревожно": "anxious",
  "тревожный": "anxious",
  "воодушевляюще": "uplifting",
  "воодушевляющий": "uplifting",
  "вдохновляюще": "inspiring",
  "вдохновляющий": "inspiring",
  "торжественно": "triumphant",
  "торжественный": "triumphant",
  "возвышенно": "sublime",
  "возвышенный": "sublime",
  "интимно": "intimate",
  "интимный": "intimate",
  "страстно": "passionate",
  "страстный": "passionate",
  "задумчиво": "contemplative",
  "задумчивый": "contemplative",
  "мечтательно": "dreamy",
  "мечтательный": "dreamy",
  "игриво": "playful",
  "игривый": "playful",
  "дерзко": "edgy",
  "дерзкий": "edgy",
  "сексуально": "sensual",
  "сексуальный": "sensual",
  "бодро": "lively",
  "бодрый": "lively",
  "расслабленно": "relaxed",
  "расслабленный": "relaxed",
  "напряженно": "tense",
  "напряженный": "tense",
  "зловеще": "ominous",
  "зловещий": "ominous",
  "величественно": "majestic",
  "величественный": "majestic",
  "нервно": "nervous",
  "нервный": "nervous",
  "беззаботно": "carefree",
  "беззаботный": "carefree",
  "уверенно": "confident",
  "уверенный": "confident",
  "дикий": "wild",
  "дико": "wild",
  "безумно": "crazy",
  "безумный": "crazy",
  "сумасшедший": "insane",
  "поп": "pop",
  "поп-музыка": "pop music",
  "рок": "rock",
  "хард-рок": "hard rock",
  "софт-рок": "soft rock",
  "прогрессив-рок": "progressive rock",
  "прог-рок": "prog rock",
  "арт-рок": "art rock",
  "психоделик-рок": "psychedelic rock",
  "джаз": "jazz",
  "смуз-джаз": "smooth jazz",
  "фри-джаз": "free jazz",
  "бибоп": "bebop",
  "кул-джаз": "cool jazz",
  "эйсид-джаз": "acid jazz",
  "джаз-фанк": "jazz-funk",
  "блюз": "blues",
  "электрик-блюз": "electric blues",
  "чикаго-блюз": "Chicago blues",
  "дельта-блюз": "delta blues",
  "хип-хоп": "hip-hop",
  "хипхоп": "hip-hop",
  "олд-скул": "old school",
  "нью-скул": "new school",
  "бум-бэп": "boom bap",
  "рэп": "rap",
  "ганста-рэп": "gangsta rap",
  "сознательный рэп": "conscious rap",
  "электро": "electronic",
  "электронная": "electronic",
  "электронный": "electronic",
  "электроника": "electronica",
  "техно": "techno",
  "минимал-техно": "minimal techno",
  "детройт-техно": "Detroit techno",
  "хаус": "house",
  "дипхаус": "deep house",
  "дип-хаус": "deep house",
  "прогрессив-хаус": "progressive house",
  "тек-хаус": "tech house",
  "тропикал-хаус": "tropical house",
  "фанки-хаус": "funky house",
  "афро-хаус": "Afro house",
  "транс": "trance",
  "вокал-транс": "vocal trance",
  "прогрессив-транс": "progressive trance",
  "псай-транс": "psytrance",
  "гоа-транс": "Goa trance",
  "драм-н-бейс": "drum and bass",
  "драмнбейс": "drum and bass",
  "джангл": "jungle",
  "ликвид": "liquid drum and bass",
  "нейрофанк": "neurofunk",
  "дабстеп": "dubstep",
  "бростеп": "brostep",
  "регги": "reggae",
  "даб": "dub",
  "дансхолл": "dancehall",
  "ска-панк": "ska punk",
  "фанк": "funk",
  "пи-фанк": "P-funk",
  "соул": "soul",
  "нео-соул": "neo-soul",
  "r&b": "R&B",
  "рнб": "R&B",
  "ритм-энд-блюз": "rhythm and blues",
  "кантри": "country",
  "кантри-рок": "country rock",
  "блюграсс": "bluegrass",
  "американа": "Americana",
  "фолк": "folk",
  "инди-фолк": "indie folk",
  "народная": "folk",
  "этно": "ethnic",
  "этническая": "world music",
  "ворлд": "world",
  "классика": "classical",
  "классическая": "classical",
  "классический": "classical",
  "неоклассика": "neoclassical",
  "барокко": "baroque",
  "ренессанс": "renaissance",
  "симфоническая": "symphonic",
  "симфонический": "symphonic",
  "камерная": "chamber",
  "опера": "opera",
  "оперетта": "operetta",
  "метал": "metal",
  "металл": "metal",
  "хеви-метал": "heavy metal",
  "трэш-метал": "thrash metal",
  "дэт-метал": "death metal",
  "блэк-метал": "black metal",
  "пауэр-метал": "power metal",
  "симфо-метал": "symphonic metal",
  "ню-метал": "nu metal",
  "металкор": "metalcore",
  "дэткор": "deathcore",
  "панк": "punk",
  "хардкор-панк": "hardcore punk",
  "поп-панк": "pop punk",
  "пост-хардкор": "post-hardcore",
  "эмо": "emo",
  "эмокор": "emocore",
  "скримо": "screamo",
  "инди": "indie",
  "инди-рок": "indie rock",
  "инди-поп": "indie pop",
  "альтернатива": "alternative",
  "альтернативный": "alternative",
  "альт-рок": "alt-rock",
  "латино": "Latin",
  "латинский": "Latin",
  "сальса": "salsa",
  "бачата": "bachata",
  "реггетон": "reggaeton",
  "кумбия": "cumbia",
  "танго": "tango",
  "босса-нова": "bossa nova",
  "самба": "samba",
  "диско": "disco",
  "ню-диско": "nu-disco",
  "итало-диско": "Italo disco",
  "синтипоп": "synthpop",
  "синти-поп": "synthpop",
  "электропоп": "electropop",
  "дарквейв": "darkwave",
  "колдвейв": "coldwave",
  "ретро": "retro",
  "80-е": "80s",
  "восьмидесятые": "80s",
  "90-е": "90s",
  "девяностые": "90s",
  "2000-е": "2000s",
  "нулевые": "2000s",
  "лоу-фай": "lo-fi",
  "лофай": "lo-fi",
  "чилл": "chill",
  "чиллаут": "chillout",
  "чилл-хоп": "chillhop",
  "амбиент": "ambient",
  "эмбиент": "ambient",
  "дарк-амбиент": "dark ambient",
  "дроун": "drone",
  "госпел": "gospel",
  "спиричуэлс": "spirituals",
  "свинг-жанр": "swing",
  "биг-бенд": "big band",
  "ска": "ska",
  "гранж": "grunge",
  "шугейз": "shoegaze",
  "дрим-поп": "dream pop",
  "постпанк": "post-punk",
  "пост-панк": "post-punk",
  "пост-рок": "post-rock",
  "пост-метал": "post-metal",
  "синтвейв": "synthwave",
  "ретровейв": "retrowave",
  "аутран": "outrun",
  "вейпорвейв": "vaporwave",
  "фьючер-бейс": "future bass",
  "фьючер-гараж": "future garage",
  "трэп": "trap",
  "трэп-музыка": "trap music",
  "футворк": "footwork",
  "джук": "juke",
  "гэридж": "UK garage",
  "грайм": "grime",
  "бейсмент": "UK bass",
  "IDM": "IDM",
  "глитч": "glitch",
  "нойз": "noise",
  "экспериментал": "experimental",
  "авангард": "avant-garde",
  "мат-рок": "math rock",
  "пост-бит": "post-beat",
  "брейкбит": "breakbeat",
  "биг-бит": "big beat",
  "брейкс": "breaks",
  "гоа": "Goa",
  "хардстайл": "hardstyle",
  "хард-дэнс": "hard dance",
  "хэппи-хардкор": "happy hardcore",
  "габбер": "gabber",
  "спидкор": "speedcore",
  "индастриал": "industrial",
  "EBM": "EBM",
  "эгбит": "aggrotech",
  "кибер-панк": "cyberpunk",
  "ки-поп": "K-pop",
  "джей-поп": "J-pop",
  "аниме": "anime",
  "игровая": "video game music",
  "саундтрек": "soundtrack",
  "кинематографический": "cinematic",
  "эпик": "epic orchestral",
  "трейлер-музыка": "trailer music",
  "мужской": "male",
  "мужчина": "male",
  "женский": "female",
  "женщина": "female",
  "голос": "vocals",
  "вокал": "vocals",
  "вокальный": "vocal",
  "поет": "singing",
  "пою": "singing",
  "спеть": "sing",
  "петь": "singing",
  "унисон": "unison harmony",
  "в унисон": "in unison",
  "хор": "choir",
  "хоровой": "choral",
  "хоровое": "choral",
  "рэпует": "rapping",
  "читает рэп": "rapping",
  "речитатив": "spoken word",
  "разговорный": "spoken",
  "шепот": "whisper",
  "шепотом": "whispered",
  "крик": "screaming",
  "кричит": "screaming",
  "орет": "shouting",
  "гроулинг": "growling",
  "гроул": "growl",
  "скрим": "scream",
  "скриминг": "screaming vocals",
  "фальцет": "falsetto",
  "бэк-вокал": "backing vocals",
  "бэк": "backing",
  "подпевка": "backing vocals",
  "дуэт": "duet",
  "трио": "trio",
  "квартет": "quartet",
  "соло-вокал": "solo vocals",
  "сопрано": "soprano",
  "альт": "alto",
  "тенор": "tenor",
  "баритон": "baritone",
  "бас-голос": "bass voice",
  "вибрато": "vibrato",
  "мелизмы": "melisma",
  "йодль": "yodeling",
  "автотюн": "auto-tune",
  "вокодер": "vocoder",
  "битбокс": "beatbox",
  "скат": "scat singing",
  "речь": "speech",
  "нарратив": "narrative",
  "рассказ": "storytelling",
};
