-- Accepted editorial batch: four independently sourced public-domain song ideas.
WITH ideas (title, full_story, hero_pov, central_conflict, emotional_arc, ending_direction, hook_direction, genres, moods, energy, themes, generator_brief, generator_story, sort_order) AS (
  VALUES
  ('Сигнал вместо приказа','Во время аварии молодой член команды ждёт недостижимого приказа от близкого человека, но понимает, что ответственность — это вовремя подать сигнал и вывести людей в безопасное место.','От первого лица, молодой член команды.','Верность привычному приказу против личной ответственности за людей рядом.','От страха к взрослой решимости.','Он включает сигнал тревоги и помогает команде уйти до того, как будет поздно.','Мигающий сигнал сквозь дым и шум.',ARRAY['Техно'],ARRAY['Напряжение'],'Высокая',ARRAY['Семья','спасение'],'Техно высокой энергии о человеке, который перестаёт ждать разрешения и спасает команду.','Во время аварии герой отказывается от слепого ожидания приказа, подаёт сигнал и берёт на себя ответственность за людей.',151),
  ('Не делай из меня трофей','На вечеринке чужой розыгрыш с личной вещью превращается в соревнование за статус. Героиня останавливает этот спектакль и возвращает всем разговор об уважении и границах.','От первого лица, героиня.','Публичный статус и чужая бравада против уважения к личным границам.','От иронии к ясной самозащите.','Она забирает себе право решать, что является шуткой, и уходит не побеждённой, а услышанной.','Заколка, которую не превратят в приз.',ARRAY['Электропоп'],ARRAY['Ирония'],'Средняя',ARRAY['Город','самоценность'],'Электропоп о светской мелочи, за которой обнаруживается право человека не быть трофеем.','Героиня прекращает статусную ссору на вечеринке и требует уважения к своим границам.',152),
  ('Свет в общем зале','Жители общего дома привыкли молчать о ночной угрозе, пока незнакомец не остаётся с ними до утра. Его спокойствие помогает всем перестать прятаться и вернуть себе общий дом.','От первого лица, один из жителей.','Привычка молчать из страха против солидарности и готовности действовать вместе.','От тревоги к общей решимости.','Утром свет остаётся включённым не из страха, а как знак, что люди больше не поодиночке.','Свет, который горит в общем зале всю ночь.',ARRAY['Рок'],ARRAY['Напряжение'],'Высокая',ARRAY['Дом','команда'],'Рок о сообществе, которое перестаёт прятать страх и возвращает себе чувство безопасности.','Незнакомец остаётся с испуганными жильцами на ночной смене, и вместе они превращают общий дом в безопасное место.',153),
  ('Рядом с тем, кого боялась','Оставшаяся одна героиня встречает сильного спутника, которого сначала боится. Совместная дорога учит её доверять не обещаниям, а поступкам, и возвращает ей смелость продолжать путь.','От первого лица, героиня.','Страх перед незнакомым союзником против потребности доверять и идти дальше.','От уязвимости к смелости.','Она идёт рядом с новым другом не потому, что страх исчез, а потому, что научилась не быть с ним один на один.','Следы двух путников на лесной дороге.',ARRAY['Эпик-рок'],ARRAY['Смелость'],'Высокая',ARRAY['Животные','дорога'],'Эпик-рок о доверии, которое возникает между человеком и тем, кого он сперва боялся.','Героиня принимает помощь неожиданного спутника и благодаря совместному пути возвращает себе смелость.',154)
)
INSERT INTO public.song_ideas (title, full_story, hero_pov, central_conflict, emotional_arc, ending_direction, hook_direction, genres, moods, energy, themes, generator_brief, generator_story, is_published, sort_order)
SELECT title, full_story, hero_pov, central_conflict, emotional_arc, ending_direction, hook_direction, genres, moods, energy, themes, generator_brief, generator_story, true, sort_order
FROM ideas;

WITH sources (title, original_key, author_name, original_title, original_language, origin_country, original_year, source_url, rights_check, music_adaptations, source_synopsis, main_image, editor_note) AS (
  VALUES
  ('Сигнал вместо приказа','felicia-hemans|casabianca','Felicia Hemans','Casabianca','English','United Kingdom',1829,'https://en.wikisource.org/wiki/Poems_That_Every_Child_Should_Know/Casabianca','Произведение опубликовано в 1829 году; Felicia Hemans умерла в 1835 году. Оригинальный английский текст находится в public domain.','[]','Ребёнок на горящем корабле ждёт приказа от отца, которого уже не может услышать.','Сигнал сквозь дым','Не использовать строки, имена, военную и трагическую развязку оригинала.'),
  ('Не делай из меня трофей','alexander-pope|the-rape-of-the-lock','Alexander Pope','The Rape of the Lock','English','United Kingdom',1714,'https://en.wikisource.org/wiki/The_Rape_of_the_Lock_(1714,_2nd_edition)','Оригинальное издание 1714 года; Alexander Pope умер в 1744 году. Текст находится в public domain.','[]','Незначительный на вид поступок — срезанная прядь волос — разрастается в светский конфликт о достоинстве и статусе.','Личная вещь, превращённая в приз','Не использовать персонажей, сатирические формулы, строки или конкретную прядь как сюжетный объект.'),
  ('Свет в общем зале','unknown|beowulf','Unknown','Beowulf','Old English','Anglo-Saxon England',700,'https://en.wikisource.org/wiki/Beowulf','Анонимная древнеанглийская поэма раннего Средневековья; оригинал находится в public domain.','["Hannah Lash — Beowulf, камерная опера (2017)"]','Герой прибывает к людям, которых ночная опасность лишила безопасности, и остаётся защитить их общий зал.','Свет в общем зале','Не использовать имена, монстров, боевые эпизоды, строки или материалы музыкальных адаптаций.'),
  ('Рядом с тем, кого боялась','edmund-spenser|the-faerie-queene-book-i-canto-iii','Edmund Spenser','The Faerie Queene, Book I, Canto III','English','England',1590,'https://en.wikisource.org/wiki/The_Faerie_Queene/Book_I/Canto_III','Оригинальное издание 1590 года; Edmund Spenser умер в 1599 году. Текст находится в public domain.','[]','Оставшаяся без спутника Уна идёт через пустынные места и обретает неожиданную защиту льва.','Следы рядом на лесной дороге','Не использовать религиозную аллегорию, имена, фэнтезийные события или строки оригинала.')
)
INSERT INTO public.song_idea_sources (idea_id, original_key, author_name, original_title, original_language, origin_country, original_year, source_url, rights_check, music_adaptations, source_synopsis, main_image, editorial_status, editor_note)
SELECT i.id, s.original_key, s.author_name, s.original_title, s.original_language, s.origin_country, s.original_year, s.source_url, s.rights_check, s.music_adaptations::jsonb, s.source_synopsis, s.main_image, 'accepted', s.editor_note
FROM sources s JOIN public.song_ideas i ON i.title = s.title
ON CONFLICT (original_key) DO NOTHING;
