import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Security: Verify request comes from service role (internal calls only)
    const authHeader = req.headers.get("Authorization");
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    
    if (authHeader !== `Bearer ${supabaseServiceKey}`) {
      return new Response(
        JSON.stringify({ error: "Unauthorized - internal use only" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { track_id, original_cover_url, track_title, genre } = await req.json();
    
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    console.log(`Generating HD cover for track: ${track_id}`);

    // Build the prompt for generating an HD cover
    const prompt = `Create a stunning, high-resolution album cover art (1920x1920 pixels) for a music track. 
    Track title: "${track_title}"
    Genre: ${genre || "electronic music"}
    
    Requirements:
    - Ultra high resolution, professional quality
    - Vibrant colors and artistic composition
    - Modern, visually striking design suitable for music streaming platforms
    - Abstract or semi-abstract artistic style
    - Should evoke emotions related to the music genre
    ${original_cover_url ? `Reference the style and mood of the original cover but enhance it significantly.` : ""}
    
    Create a 1920x1920 aspect ratio album artwork.`;

    // Use Lovable AI with image generation model
    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-3-pro-image-preview",
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      
      if (response.status === 429) {
        throw new Error("Rate limit exceeded. Please try again later.");
      }
      if (response.status === 402) {
        throw new Error("Payment required. Please add funds to your workspace.");
      }
      throw new Error(`AI gateway error: ${response.status}`);
    }

    const data = await response.json();
    const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!imageUrl) {
      throw new Error("No image generated by AI");
    }

    console.log("HD cover generated successfully");

    // Upload the base64 image to Supabase Storage
    const base64Data = imageUrl.replace(/^data:image\/\w+;base64,/, "");
    const imageBuffer = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));
    
    const fileName = `hd-covers/${track_id}-${Date.now()}.png`;
    
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from("tracks")
      .upload(fileName, imageBuffer, {
        contentType: "image/png",
        upsert: true,
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      throw new Error("Failed to upload HD cover to storage");
    }

    const { data: publicUrl } = supabase.storage
      .from("tracks")
      .getPublicUrl(fileName);

    // Update the track_addons table with the result
    const { error: updateError } = await supabase
      .from("track_addons")
      .update({
        result_url: publicUrl.publicUrl,
        status: "completed",
        updated_at: new Date().toISOString(),
      })
      .eq("track_id", track_id)
      .eq("addon_service_id", (
        await supabase
          .from("addon_services")
          .select("id")
          .eq("name", "large_cover")
          .single()
      ).data?.id);

    if (updateError) {
      console.error("Update addon error:", updateError);
    }

    return new Response(
      JSON.stringify({
        success: true,
        cover_url: publicUrl.publicUrl,
        message: "HD cover generated successfully",
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("generate-hd-cover error:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
